<a href="https://colab.research.google.com/github/saswithaparitala/CS-lab/blob/main/Anova_two_way.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
A=np.array([13,7,9,3])
B=np.array([6,6,3,1])
C=np.array([11,5,15,5])
d=np.sum(A)
e=np.sum(B)
f=np.sum(C)
print(d)
print(e)
print(f)
Ti=np.array([d,e,f])
print(Ti)
a=d**2
b=e**2
c=f**2
Ti_2=np.array([a,b,c])
print(Ti_2)

32
16
36
[32 16 36]
[1024  256 1296]


In [4]:
r=np.array([13,6,11])
x=np.array([7,6,5])
y=np.array([9,3,15])
z=np.array([3,1,5])
B1=np.sum(r)
print(B1)
B2=np.sum(x)
B3=np.sum(y)
B4=np.sum(z)
print(B2)
print(B3)
print(B4)
Bj=np.array([B1,B2,B3,B4])
print(Bj)
Bj_2=np.array([B1**2,B2**2,B3**2,B4**2])
print(Bj_2)
sigma_Bj_2=np.sum(Bj_2)
print(sigma_Bj_2)
G=np.sum(Ti)
print(G)
sigma_Ti_2=np.sum(Ti_2)
print(sigma_Ti_2)

30
18
27
9
[30 18 27  9]
[900 324 729  81]
2034
84
2576


In [5]:
s=0
for i in range(len(A)):
  s=s+A[i]**2
for j in range(len(B)):
  s=s+B[j]**2
for g in range(len(C)):
  s=s+C[g]**2
print(s) #row sum of squares
CF=G**2/(len(A)+len(B)+len(C))
print(CF)
SST=s-CF
print(SST)
SSTR=(sigma_Ti_2/len(A))-CF
print(SSTR)
k=3
h=4
SSB=(sigma_Bj_2/k)-CF
print(SSB)
SSE=SST-SSTR-SSB
print(SSE)

786
588.0
198.0
56.0
90.0
52.0


In [6]:
sstr=SSTR/(k-1)
ssb=SSB/(h-1)
sse=SSE/((k-1)*(h-1))
print(sstr)
print(ssb)
print(sse)

28.0
30.0
8.666666666666666


In [7]:
dataset={"sourse of variance":['treatements','blocks','errors'],"sum of squares":[SSTR,SSB,SSE],"degress of freedom":[k-1,h-1,(k-1)*(h-1)],"mean sum of squares":[sstr,ssb,sse],"variance ratio":[sstr/sse,ssb/sse,'']}
df=pd.DataFrame(dataset)
print(df)

  sourse of variance  sum of squares  degress of freedom  mean sum of squares  \
0        treatements            56.0                   2            28.000000   
1             blocks            90.0                   3            30.000000   
2             errors            52.0                   6             8.666667   

  variance ratio  
0       3.230769  
1       3.461538  
2                 


In [8]:
table_tr=st.f.ppf(0.95,k-1,(k-1)*(h-1))
print("table value realated to treatements :",table_tr)
if (sstr/sse)>table_tr:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")
table_b=st.f.ppf(0.95,h-1,(k-1)*(h-1))
print("table value realated to blocks :",table_b)
if (ssb/sse)>table_b:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

table value realated to treatements : 5.143252849784718
accept null hypothesis
table value realated to blocks : 4.757062663089414
accept null hypothesis
